# 如果觉得好用，请收藏或则分享本站
swagger: '2.0'
info:
  title: onp/plugchain/v1/query.proto
  version: version not set
consumes:
  - application/json
produces:
  - application/json
paths:
  /onp/plugchain/v1/token_list:
    get:
      operationId: TokenList
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/onp.plugchain.v1.QueryTokenListResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/grpc.gateway.runtime.Error'
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
      tags:
        - Query
  '/onp/plugchain/v1/tokens_addr/{address}':
    get:
      operationId: TokensByAccAddr
      responses:
        '200':
          description: A successful response.
          schema:
            $ref: '#/definitions/onp.plugchain.v1.QueryTokensByAccAddrResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/grpc.gateway.runtime.Error'
      parameters:
        - name: address
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        title: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/google.protobuf.Any'
  onp.plugchain.v1.MsgCreateToken:
    type: object
    properties:
      symbol:
        type: string
      original_symbol:
        type: string
      description:
        type: string
      whole_name:
        type: string
      total_supply:
        type: string
      owner:
        type: string
      founder:
        type: string
      decimal:
        type: string
        format: uint64
      mintable:
        type: boolean
  onp.plugchain.v1.QueryTokenListResponse:
    type: object
    properties:
      tokens:
        type: array
        items:
          $ref: '#/definitions/onp.plugchain.v1.MsgCreateToken'
      pagination:
        $ref: '#/definitions/cosmos.base.query.v1beta1.PageResponse'
  onp.plugchain.v1.QueryTokensByAccAddrResponse:
    type: object
    properties:
      token:
        type: array
        items:
          $ref: '#/definitions/onp.plugchain.v1.MsgCreateToken'
